services:
  - type: web
    name: homefirst-recalls-automation
    runtime: node
    buildCommand: apt-get update && apt-get install -y libreoffice && npm install
    startCommand: node server.js
    envVars:
      - key: SLACK_TOKEN
        value: xoxb-9907482923348-10951643847783-39Gzl6BhqukZZrDUVayI6dHY
      - key: SLACK_CHANNEL
        value: C0AUBTULV8E
      - key: WEBHOOK_SECRET
        value: homefirst2026
      - key: NODE_ENV
        value: production
